#!/usr/bin/env bash

set -e

# Tester image
# Contains PTF and tvutils libraries, as well as P4RT, gNMI, and TV Python bindings
TESTER_DOCKER_IMG=stratumproject/testvectors:ptf

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"
ROOT_DIR=${DIR}/../..

if [[ -z "${ONOS_ROOT}" ]]; then
    echo "ERROR: ONOS_ROOT env not defined"
    exit 1
fi
if [[ -z "${FABRIC_TOFINO}" ]]; then
    echo "ERROR: FABRIC_TOFINO env not defined"
    exit 1
fi

# Clean up old logs (if any)
rm -rf "${DIR}"/log
mkdir "${DIR}"/log

rnd=${RANDOM}

# tester
# Run and show log
testerRunName=tester-${rnd}
echo "*** Starting ${testerRunName}..."
# Do not attach stdin if running in an environment without it (e.g., Jenkins)
it=$(test -t 0 && echo "-it" || echo "-t")
docker run --name ${testerRunName} ${it} --privileged --rm \
    -v "${ROOT_DIR}":/fabric-p4test \
    -v "${ONOS_ROOT}":/onos -e ONOS_ROOT=/onos \
    -v "${FABRIC_TOFINO}":/fabric-tofino -e FABRIC_TOFINO=/fabric-tofino \
    "${TESTER_DOCKER_IMG}" \
    bash /fabric-p4test/run/tv/start_test.sh "${FABRIC_PROFILE}" ${@}
